import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Image from 'next/image';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-[#09061A]  overflow-x-hidden relative font-montserrat`}> 
          <Image src="/background blur.png" width={1140} height={462} alt="" className='object-cover absolute top-0 left-0 right-0 w-full h-[100vh] border border-white'/>
        <div className="containerbox">
          <Navbar />
          <main className=''>      
            {children}
            </main>
          <Footer />
          </div> 
      </body>
    </html>
  );
}
